name: CI & Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Lint & Format
        run: |
          go fmt ./...
          go vet ./...
      - name: Unit Tests
        run: |
          go test ./ca-service/...
          go test ./acme-server/...
          go test ./signing-service/...
          go test ./cli/...

  integration:
    name: End-to-End Integration
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build Binaries
        run: |
          go build -o ca-service/ca-service ./ca-service
          go build -o acme-server/acme-server ./acme-server
          go build -o signing-service/signing-service ./signing-service
          go build -o cli/cli ./cli
      - name: Start CA Service
        run: nohup ./ca-service/ca-service &
      - run: sleep 5
      - name: Start ACME Server
        run: nohup ./acme-server/acme-server &
      - run: sleep 5
      - name: Start Signing Service
        run: nohup ./signing-service/signing-service &
      - run: sleep 5
      - name: Prepare SBOM & Provenance
        run: |
          echo '{}' > sbom.json
          echo '{}' > provenance.json
      - name: Run Signing CLI
        run: |
          ./cli/cli --artifact cli/cli --sbom sbom.json --provenance provenance.json --server https://localhost:7000
      - name: Clean up Services
        run: pkill ca-service || true; pkill acme-server || true; pkill signing-service || true